### ISSUE TITLE
Please share a build apk, so we can test or use the app

### ISSUE THREAD

**Issue by swarupbhc** [Haidar0096/Sound-Changer#1]
Please share a build apk, so we can test or use the app

**Comment by Haidar0096** [comment]
@swarup13 Hello, you can run the command flutter build apk --split-per-abi in the project's root directory, and then an apk will be generated per device, If you can't do it tell me to share the apk with you. Thanks.

**Comment by Haidar0096** [comment]
I have added a small demo video to the readme to demonstrate the app, and as I said you can run the command ` flutter build apk --split-per-abi` and an apk will be generated to you. So I will close this issue for now.
